### ISSUE TITLE
Projekt Setup 

### ISSUE THREAD

**Issue by MadlyCaptaingreen** [itf191-raum3/raum3-thegame#1]
In diesen Issue werden die erste Schritte welche zum Setup und start des Projekt benötigt werden aufgelistet. 

Aktueller Status der einzelnen Punkte

- [X] Projekt in Github anlegen und Konfigurieren @chipskater 
- [X] Github Team Board anlegen und Konfigurieren @MadlyCaptaingreen 
- [x] Erstes Design der Anwendung entwickeln 
- [x] Einigung auf Testengine 
- #2 Erstellen der Pipeline in Github @chipskater

**Comment by chipskater** [comment]
Kann man den Punkt "Erstes Design der Anwendung entwickeln" als in #8 und #9 ausgelagert sehen? @MiguelKrimp

**Comment by MiguelKrimp** [comment]
Kommt drauf an, was genau mit "Design" gemeint ist. 
Bei grafischem Design würde es der Entwicklung der Widgets vorangehen, damit man auch weiß, wie es am Ende aussehen soll.
Da könnten wir aber auch im Nachhinein und evtl. nach Kundenabsprache nochmal drüber schauen. Sollte keinen großen Aufwand bedeuten.
