### ISSUE TITLE
Dokumentation erstellen

### ISSUE THREAD

**Issue by MiguelKrimp** [itf191-raum3/raum3-thegame#7]
Das Projekt sollte eine Dokumentation besitzen.
Die Dokumentation sollte automatisch aus Kommentaren im Source code generiert werden.
Dafür kann zB typedoc (https://github.com/TypeStrong/typedoc) verwendet werden.

**Comment by MadlyCaptaingreen** [comment]
Die Dokumentation von Front und Backend liegt nun in dem Ordner Docs. 

TODO: 

- [ ] Automatische Generation der Docs über die Pipeline

**Comment by MadlyCaptaingreen** [comment]
Überlegung zussammen führen der Doc in einen Ordner anstatt Front und Backend Ordner

**Comment by MadlyCaptaingreen** [comment]
Die Docs werden nun automatisch in der Pipeline erzeugt und am Ende als artifact zum herunterladen zur verfügung gestellt. 

### **Funktioniert nur mit node 15 => node 14 wirft noch Fehler **
