### ISSUE TITLE
Choice Exercise Widget

### ISSUE THREAD

**Issue by MiguelKrimp** [itf191-raum3/raum3-thegame#8]
Für Choice Exercises benötigt man ein Widget, in dem die Aufgabe dargestellt wird und bearbeitet werden kann.

**Comment by MadlyCaptaingreen** [comment]
Erste initialfeatures für das Choice Exercise Widget erstellt.

**Comment by MadlyCaptaingreen** [comment]
Grundfunktionen der Choice Exercise funktionieren. 

TODO: 

- [  ] Anpassen Layout
- [  ] Kommunikation mit dem Backend 
- [  ] Anpassen an die Welcome Page

**Comment by MiguelKrimp** [comment]
Überarbeitet und in main gemerged
